Repository Human-Connection/Human-Connection, pull requests merged in 2019-10, with the labels that each got.

#1878 🍰 Refactor Database for Reporting with specific information
  backend/src/middleware/permissionsMiddleware.js
  backend/src/middleware/validation/validationMiddleware.js
  backend/src/schema/index.js
  backend/src/schema/resolvers/reports.js
  backend/src/schema/resolvers/reports.spec.js
  backend/src/schema/types/schema.gql
  backend/src/schema/types/type/REPORTED.gql
  backend/src/seed/seed-db.js
  cypress/integration/common/report.js
  neo4j/change_report_node_to_relationship.sh
  webapp/components/Modal/ReportModal.vue
  webapp/graphql/Moderation.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/moderation/index.vue
Labels: backend, frontend

#1972 🍰 Translate texts for pinning a post to German
  webapp/locales/de.json
Labels: bug, frontend

#2017 new terms and conditions
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/terms-and-conditions.vue
Labels: core

#2027 🍰 New terms and conditions version 0.0.3
  cypress/constants/terms-and-conditions-version.js
  cypress/integration/common/report.js
  cypress/integration/common/steps.js
  webapp/components/Registration/CreateUserAccount.spec.js
  webapp/constants/terms-and-conditions-version.js
  webapp/pages/terms-and-conditions.vue
Labels: bug, frontend

#2093 deleted posts no longer displayed in user profile
  backend/src/middleware/softDelete/softDeleteMiddleware.js
Labels: bug
