Repository Human-Connection/Human-Connection, pull requests merged in 2019-06, with the labels that each got.

#698 Fix upload large file sizes bug
  webapp/components/Upload/index.vue
  webapp/components/Upload/spec.js
Labels: bug

#714 Deploy maintenance worker to dockerhub automatically with smaller split size
  deployment/legacy-migration/maintenance-worker/migration/mongo/.env
  deployment/legacy-migration/maintenance-worker/migration/mongo/export.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/import.sh
  docker-compose.maintenance.yml
  scripts/docker_push.sh
Labels: enhancement

#609 Delete Comment
  backend/src/middleware/permissionsMiddleware.js
  backend/src/resolvers/comments.js
  backend/src/resolvers/comments.spec.js
  backend/src/resolvers/socialMedia.spec.js
  webapp/components/Comment.spec.js
  webapp/components/Comment.vue
  webapp/components/ContentMenu.vue
  webapp/components/Modal.spec.js
  webapp/components/Modal.vue
  webapp/components/Modal/DeleteModal.spec.js
  webapp/components/Modal/DeleteModal.vue
  webapp/components/Modal/DisableModal.spec.js
  webapp/components/Modal/DisableModal.vue
  webapp/components/Modal/ReportModal.spec.js
  webapp/components/Modal/ReportModal.vue
  webapp/components/PostCard/index.vue
  webapp/components/comments/CommentList/index.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/mixins/PostMutationHelpers.js
  webapp/package.json
  webapp/pages/index.vue
  webapp/pages/post/_id/_slug/index.spec.js
  webapp/pages/post/_id/_slug/index.vue
  webapp/pages/post/_id/_slug/more-info.vue
  webapp/pages/profile/_id/_slug.spec.js
  webapp/pages/profile/_id/_slug.vue
Labels: feature

#725 Don't remove middlewares in production
  backend/src/middleware/index.js
Labels: bug

#729 User can not anymore delete Comments of others
  backend/src/middleware/permissionsMiddleware.js
  backend/src/resolvers/comments.spec.js
Labels: backend, bug

#752 402 userprofile shouted tab 2
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/profile/_id/_slug.vue
Labels: frontend

#699 269 filter by followed users
  cypress/integration/common/steps.js
  webapp/components/FilterMenu/FilterMenu.spec.js
  webapp/components/FilterMenu/FilterMenu.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/index.vue
Labels: feature

#754 402 userprofil tab click function
  backend/src/schema/types/type/User.gql
  webapp/components/LoadMore.vue
  webapp/graphql/UserProfile/Post.js
  webapp/graphql/UserProfile/User.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/profile/_id/_slug.spec.js
  webapp/pages/profile/_id/_slug.vue
Labels: frontend

#830 2019/kw24/import_images_improvements
  deployment/legacy-migration/maintenance-worker/binaries/.env
  deployment/legacy-migration/maintenance-worker/binaries/import_legacy_uploads
Labels: enhancement

#786 [Bug] Untranslated Texts in Post Page #764
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
Labels: bug

#856 Fix a text description for the filter bubble
  webapp/components/FilterMenu/FilterMenu.vue
  webapp/locales/de.json
  webapp/locales/en.json
Labels: feature

#829 🍰 2019/kw24/fix_imported_img_urls
  backend/src/middleware/fixImageUrlsMiddleware.js
  backend/src/middleware/fixImageUrlsMiddleware.spec.js
  backend/src/middleware/index.js
  deployment/legacy-migration/maintenance-worker/migration/neo4j/badges.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/users.cql
  webapp/package.json
Labels: bug, enhancement

#863 🍰 2019/kw25/improve_import_accuracy
  deployment/legacy-migration/maintenance-worker/migration/mongo/export.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/badges/badges.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/badges/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/categories/categories.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/categories/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/comments/comments.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/comments/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions/contributions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/delete_all.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/emotions/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/emotions/emotions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/follows/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/follows/follows.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/import.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/invites/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/invites/invites.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/notifications/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/notifications/notifications.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/organizations/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/organizations/organizations.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/pages/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/pages/pages.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/projects/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/projects/projects.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/settings/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/settings/settings.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/shouts/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/shouts/shouts.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/status/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/status/status.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/systemnotifications/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/systemnotifications/systemnotifications.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/users/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/users/users.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/userscandos/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/userscandos/userscandos.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/usersettings/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/usersettings/usersettings.cql
Labels: bug, enhancement
