Repository Human-Connection/Human-Connection, pull requests merged in 2019-05, with the labels that each got.

#452 [WIP] 451 lokalise unlocalised texts
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/login.vue
Labels: bug, enhancement

#569 2019/kw19/codecov
  .codecov.yml
  .travis.yml
  docker-compose.travis.yml
Labels: Feature, enhancement

#574 2019/kw19/codecov
  .codecov.yml
  backend/package.json
  webapp/.babelrc
  webapp/package.json
Labels: discussion, enhancement

#535 Delete SocialMedia
  backend/src/middleware/permissionsMiddleware.js
  backend/src/resolvers/socialMedia.js
  backend/src/resolvers/socialMedia.spec.js
  cypress/integration/common/settings.js
  cypress/integration/user_profile/SocialMedia.feature
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/settings/my-social-media.spec.js
  webapp/pages/settings/my-social-media.vue
Labels: Feature, backend, frontend

#478 2019/kw15/user can change its username to emptystring
  backend/package.json
  backend/src/middleware/permissionsMiddleware.spec.js
  backend/src/middleware/slugify/uniqueSlug.js
  backend/src/middleware/slugify/uniqueSlug.spec.js
  backend/src/middleware/slugifyMiddleware.spec.js
  backend/src/middleware/userMiddleware.js
  backend/src/middleware/userMiddleware.spec.js
  backend/src/resolvers/user_management.spec.js
  backend/src/schema.graphql
  backend/src/seed/factories/users.js
  webapp/components/User/index.spec.js
  webapp/components/User/index.vue
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/it.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/pages/profile/_id/_slug.vue
  webapp/pages/settings/index.spec.js
  webapp/pages/settings/index.vue
Labels: bug, enhancement

#575 Revert tiptap upgrade
  webapp/package.json
  webapp/yarn.lock
Labels: bug

#499 296 image component
  webapp/components/Badges.vue
  webapp/components/Empty.vue
  webapp/components/Image/index.vue
  webapp/components/Image/spec.js
  webapp/components/RelativeDateTime/spec.js
  webapp/components/Tag/spec.js
  webapp/components/User/spec.js
  webapp/pages/login.vue
  webapp/pages/logout.vue
  webapp/pages/settings/my-social-media.vue
  webapp/static/img/badges/fundraisingbox_de_airship.svg
  webapp/static/img/badges/fundraisingbox_de_alienship.svg
  webapp/static/img/badges/fundraisingbox_de_balloon.svg
  webapp/static/img/badges/fundraisingbox_de_bigballoon.svg
  webapp/static/img/badges/fundraisingbox_de_crane.svg
  webapp/static/img/badges/fundraisingbox_de_glider.svg
  webapp/static/img/badges/fundraisingbox_de_helicopter.svg
  webapp/static/img/badges/fundraisingbox_de_starter.svg
  webapp/static/img/badges/indiegogo_en_bear.svg
  webapp/static/img/badges/indiegogo_en_panda.svg
  webapp/static/img/badges/indiegogo_en_rabbit.svg
  webapp/static/img/badges/indiegogo_en_racoon.svg
  webapp/static/img/badges/indiegogo_en_rhino.svg
  webapp/static/img/badges/indiegogo_en_tiger.svg
  webapp/static/img/badges/indiegogo_en_turtle.svg
  webapp/static/img/badges/indiegogo_en_whale.svg
  webapp/static/img/badges/indiegogo_en_wolf.svg
  webapp/static/img/badges/user_role_admin.svg
  webapp/static/img/badges/user_role_developer.svg
  webapp/static/img/badges/user_role_moderator.svg
  webapp/static/img/badges/wooold_de_bee.svg
  webapp/static/img/badges/wooold_de_butterfly.svg
  webapp/static/img/badges/wooold_de_double_rainbow.svg
  webapp/static/img/badges/wooold_de_end_of_rainbow.svg
  webapp/static/img/badges/wooold_de_flower.svg
  webapp/static/img/badges/wooold_de_lifetree.svg
  webapp/static/img/badges/wooold_de_magic_rainbow.svg
  webapp/static/img/badges/wooold_de_super_founder.svg
Labels: enhancement

#551 2019/kw15/change password strength
  webapp/components/ChangePassword.vue
  webapp/components/Password/Change.spec.js
  webapp/components/Password/Change.vue
  webapp/components/Password/Strength.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/package.json
  webapp/pages/settings/security.vue
  webapp/yarn.lock
Labels: Feature

#587 Update ds-avatar size to use small
  webapp/components/User/index.vue
  webapp/layouts/default.vue
Labels: bug

#556 Write component tests for CommentForm.vue
  webapp/components/comments/CommentForm/index.vue
  webapp/components/comments/CommentForm/spec.js
Labels: enhancement

#595 Delete posts
  webapp/components/ContentMenu.vue
  webapp/components/Modal.vue
  webapp/components/Modal/DeleteModal.spec.js
  webapp/components/Modal/DeleteModal.vue
  webapp/locales/en.json
  webapp/locales/es.json
Labels: duplicate

#594 Revert logout.vue
  webapp/pages/logout.vue
Labels: bug

#596 Refactoring validation middleware
  backend/src/middleware/index.js
  backend/src/middleware/userMiddleware.js
  backend/src/middleware/validUrlMiddleware.js
  backend/src/middleware/validation/index.js
  backend/src/resolvers/users.spec.js
Labels: bug

#573 Docs 354 kubernetes cron job for backups
  SUMMARY.md
  deployment/human-connection/deployment-backend.yaml
  deployment/human-connection/deployment-neo4j.yaml
  deployment/volumes/README.md
  deployment/volumes/neo4j-offline-backup/README.md
  deployment/volumes/reclaim-policy/README.md
  deployment/volumes/velero/README.md
  deployment/volumes/volume-snapshots/README.md
  deployment/volumes/volume-snapshots/digital-ocean-volume-snapshots.png
  deployment/volumes/volume-snapshots/neo4j-data.yaml
  deployment/volumes/volume-snapshots/snapshot.yaml
Labels: Feature, enhancement

#626 Refactor to use <img> instead of <hc-image> component for images
  webapp/components/Empty.vue
Labels: bug

#616 Fix wrong screenshot in kubernetes docs
  deployment/digital-ocean/https/README.md
  deployment/digital-ocean/https/ip-address.png
Labels: bug

#633 🍰 2019/kw21/github_templates_update
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#622 🍰 2019/kw20/fix_post_card_design
  webapp/components/Category/index.vue
  webapp/components/PostCard/index.vue
  webapp/components/Ribbon/index.spec.js
  webapp/components/Ribbon/index.vue
  webapp/components/User/index.vue
  webapp/locales/de.json
  webapp/pages/post/_id/_slug/index.vue
Labels: enhancement

#644 Change ds-avatar size to x-large
  webapp/pages/profile/_id/_slug.vue
Labels: bug

#636 Image upload backend implementation
  backend/package.json
  backend/public/uploads/.gitkeep
  backend/src/graphql-schema.js
  backend/src/middleware/notifications/extractIds/index.js
  backend/src/middleware/notifications/extractIds/spec.js
  backend/src/middleware/notifications/index.js
  backend/src/middleware/validation/index.js
  backend/src/resolvers/fileUpload/index.js
  backend/src/resolvers/fileUpload/spec.js
  backend/src/resolvers/posts.js
  backend/src/resolvers/users.js
  backend/src/resolvers/users.spec.js
  backend/src/schema.graphql
Labels: feature

#585 More descriptive minikube setup instructions
  deployment/human-connection/README.md
Labels: enhancement

#693 689 fix broken image urls after upload
  webapp/components/Avatar/Avatar.spec.js
  webapp/components/Avatar/Avatar.vue
  webapp/components/User/index.vue
  webapp/layouts/default.vue
  webapp/pages/profile/_id/_slug.vue
Labels: bug

#694 🍰 2019/kw22/alpha_data_export
  deployment/legacy-migration/maintenance-worker/binaries/import_legacy_db
  deployment/legacy-migration/maintenance-worker/migration/mongo/.env
  deployment/legacy-migration/maintenance-worker/migration/mongo/export.sh
  deployment/legacy-migration/maintenance-worker/migration/mongo/import.sh
Labels: enhancement, feature

#696 Run coverage only if requested
  .travis.yml
  backend/package.json
  webapp/package.json
Labels: enhancement

#662 Fix duplicate tags by using the name as the id
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions.cql
Labels: bug

#697 🍰 2019/kw22/alpha_data_import
  deployment/legacy-migration/maintenance-worker/migration/neo4j/.env
  deployment/legacy-migration/maintenance-worker/migration/neo4j/badges.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/categories.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/comments.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/follows.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/import.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/shouts.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/users.cql
Labels: enhancement, feature

#702 🍰 Avoid deletion of entire namespace by accident
  deployment/human-connection/README.md
  deployment/legacy-migration/README.md
  deployment/legacy-migration/maintenance-worker.yaml
  deployment/legacy-migration/maintenance-worker/Dockerfile
  deployment/namespace.yaml
  deployment/volumes/uploads.yaml
Labels: bug, enhancement
