Repository Human-Connection/Human-Connection, pull requests merged in 2019-08, with the labels that each got.

#1184 changes and history template, english, german
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/changelog.vue
Labels: feature

#1190 add page code-of-conduct, english and german
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/code-of-conduct.vue
Labels: feature

#1175 edit layout default for guests
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/nuxt.config.js
  webapp/pages/data-privacy.vue
  webapp/pages/login.vue
  webapp/pages/logout.vue
Labels: feature

#1185 Fix terms and conditions template, english and german
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/terms-and-conditions.vue
Labels: feature

#1174 Add static page for data privacy
  webapp/pages/data-privacy.vue
Labels: feature

#1233 🍰 [Bugfix] Fix filter menu and refactor default layout
  webapp/components/FilterMenu/FilterMenu.spec.js
  webapp/components/FilterMenu/FilterMenu.vue
  webapp/components/FilterPosts/FilterPosts.spec.js
  webapp/components/FilterPosts/FilterPosts.vue
  webapp/components/FilterPosts/FilterPostsMenuItems.vue
  webapp/layouts/default.vue
  webapp/pages/index.spec.js
  webapp/pages/index.vue
  webapp/store/default.js
  webapp/store/postsFilter.js
  webapp/store/postsFilter.spec.js
Labels: bug, frontend

#1244 🍰 454 Lokalise / translate all unlocalised Texts / Translations / Languages
  cypress/integration/administration/TagsAndCategories.feature
  package.json
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/admin/categories.vue
  webapp/pages/admin/index.vue
  webapp/pages/admin/tags.vue
  webapp/pages/admin/users.vue
  webapp/pages/post/_id/_slug/more-info.vue
  webapp/yarn.lock
Labels: frontend

#1018 🍰 Send out notifications on CreateComment
  backend/src/middleware/handleHtmlContent/handleContentData.js
  backend/src/middleware/handleHtmlContent/handleContentData.spec.js
  backend/src/schema/resolvers/notifications.spec.js
  backend/src/schema/types/schema.gql
  backend/src/schema/types/type/Notification.gql
  backend/src/seed/seed-db.js
  cypress/integration/common/steps.js
  webapp/components/Comment.vue
  webapp/components/CommentForm/CommentForm.spec.js
  webapp/components/CommentForm/CommentForm.vue
  webapp/components/Editor/Editor.spec.js
  webapp/components/Editor/Editor.vue
  webapp/components/notifications/Notification/Notification.spec.js
  webapp/components/notifications/Notification/Notification.vue
  webapp/components/notifications/Notification/index.vue
  webapp/components/notifications/NotificationList/NotificationList.spec.js
  webapp/components/notifications/NotificationList/NotificationList.vue
  webapp/components/notifications/NotificationMenu/NotificationMenu.spec.js
  webapp/components/notifications/NotificationMenu/NotificationMenu.vue
  webapp/graphql/User.js
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/nuxt.config.js
  webapp/plugins/vue-filters.js
  webapp/store/auth.js
  webapp/store/notifications.js
Labels: backend, feature, frontend

#1372 🍰 454 Lokalise unlocalised texts and fixes texts
  webapp/components/Registration/Signup.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/admin/invite.vue
  webapp/pages/profile/_id/_slug.vue
Labels: bug, frontend

#1270 🍰 1062 notification about comment on post
  backend/src/middleware/handleHtmlContent/handleContentData.js
  backend/src/middleware/handleHtmlContent/handleContentData.spec.js
  backend/src/middleware/hashtags/extractHashtags.js
  backend/src/middleware/hashtags/extractHashtags.spec.js
  backend/src/middleware/hashtags/hashtagsMiddleware.js
  backend/src/middleware/hashtags/hashtagsMiddleware.spec.js
  backend/src/middleware/index.js
  backend/src/middleware/notifications/mentions/extractMentionedUsers.js
  backend/src/middleware/notifications/mentions/extractMentionedUsers.spec.js
  backend/src/middleware/notifications/notificationsMiddleware.js
  backend/src/middleware/notifications/notificationsMiddleware.spec.js
  backend/src/models/Notification.js
  backend/src/schema/resolvers/notifications.spec.js
  backend/src/schema/types/enum/ReasonNotification.gql
  backend/src/schema/types/type/Notification.gql
  backend/src/seed/factories/index.js
  webapp/components/notifications/Notification/Notification.spec.js
  webapp/components/notifications/Notification/Notification.vue
  webapp/graphql/User.js
  webapp/locales/de.json
  webapp/locales/en.json
Labels: backend, feature, frontend

#1407 Increase nginx client max body size, split size legacy migration
  deployment/digital-ocean/https/templates/ingress.template.yaml
  deployment/legacy-migration/maintenance-worker/migration/mongo/.env
Labels: bug
