Repository Human-Connection/Human-Connection, pull requests merged in 2019-07, with the labels that each got.

#787 Add teaser image to contribution form
  backend/package.json
  backend/src/schema/resolvers/fileUpload/index.js
  backend/src/schema/types/scalar/Upload.gql
  backend/yarn.lock
  webapp/components/ContributionForm/ContributionForm.spec.js
  webapp/components/ContributionForm/index.vue
  webapp/components/TeaserImage/TeaserImage.spec.js
  webapp/components/TeaserImage/TeaserImage.vue
  webapp/components/Upload/index.vue
  webapp/graphql/PostMutations.js
  webapp/pages/post/_id/_slug/index.spec.js
  webapp/pages/post/_id/_slug/index.vue
  webapp/pages/post/create.vue
  webapp/pages/profile/_id/_slug.vue
Labels: feature

#935 Patch cypher injection vulnerability
  backend/src/schema/resolvers/users.spec.js
  backend/src/schema/types/schema.gql
  webapp/components/DeleteData/DeleteData.vue
Labels: security

#905 region and place is no longer created twice.
  backend/src/middleware/nodes/locations.js
Labels: bug

#933 907 mobile responsive menu navbar
  webapp/components/SearchInput.vue
  webapp/layouts/default.vue
Labels: feature, frontend

#908 the one-time reporting of a user, post or comment
  backend/src/schema/resolvers/reports.js
  backend/src/schema/resolvers/reports.spec.js
  backend/src/seed/factories/reports.js
  webapp/components/ContentMenu.vue
  webapp/components/Modal/ReportModal.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/fr.json
Labels: bug

#864 🐛 [Bug] : long comments can be folded up and down
  .gitignore
  webapp/components/Comment.vue
  webapp/graphql/CommentMutations.js
  webapp/graphql/PostCommentsQuery.js
  webapp/locales/de.json
  webapp/locales/en.json
Labels: bug

#963 long links and content is wrapped
  webapp/layouts/default.vue
Labels: bug

#976 large images are set to maximum height
  webapp/components/PostCard/index.vue
Labels: bug

#958 🐛 [Bug] full ads width use with small devices
  webapp/assets/styles/main.scss
  webapp/layouts/default.vue
Labels: bug

#999 footer created imprint and all language ok
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/locales/es.json
  webapp/locales/fr.json
  webapp/locales/it.json
  webapp/locales/nl.json
  webapp/locales/pl.json
  webapp/locales/pt.json
  webapp/pages/admin.vue
  webapp/pages/changelog.vue
  webapp/pages/imprint.vue
  webapp/pages/privacy.vue
  webapp/pages/terms-and-conditions.vue
Labels: feature

#944 🍰 2019/kw27/data_import_emotions
  backend/src/schema/types/enum/Emotion.gql
  backend/src/schema/types/type/EMOTED.gql
  backend/src/schema/types/type/Post.gql
  backend/src/schema/types/type/User.gql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/emotions/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/emotions/emotions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/follows/delete.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/import.sh
Labels: enhancement, feature

#968 polish language on current status
  webapp/locales/pl.json
Labels: bug

#969 Filter posts by category
  backend/src/schema/resolvers/posts.spec.js
  cypress/integration/administration/TagsAndCategories.feature
  cypress/integration/common/profile.js
  webapp/components/CategoriesSelect/CategoriesSelect.vue
  webapp/components/FilterPosts/FilterPosts.spec.js
  webapp/components/FilterPosts/FilterPosts.vue
  webapp/components/FilterPosts/FilterPostsMenuItems.vue
  webapp/components/notifications/NotificationMenu/index.vue
  webapp/graphql/CategoryQuery.js
  webapp/graphql/PostQuery.js
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/index.vue
  webapp/store/posts.js
Labels: backend, feature, frontend

#1080 Created imprint page, added English translations
  webapp/locales/en.json
Labels: feature
