Repository Human-Connection/Human-Connection, pull requests merged in 2019-04, with the labels that each got.

#339 2019/kw14/fixed_windows_build_docu_fixed_server_start_text
  backend/README.md
  backend/package.json
  backend/src/index.js
Labels: PR: unreviewed, bug

#360 2019/kw14/GitHub issue pullrequest templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: DevOps, PR: unreviewed, enhancement

#435 2019/kw15/post_make_menu_sticky
  webapp/pages/post/_id.vue
Labels: bug

#437 2019/kw15/disabled_post_fix_disabled_border_z-index
  webapp/components/PostCard.vue
Labels: bug

#443 2019/kw15/Access_Settings_from_Profile_as_Owner
  webapp/components/ContentMenu.vue
Labels: Feature, bug

#438 2019/kw15/new_post_button_position
  webapp/pages/index.vue
Labels: bug

#440 2019/kw15/design_differences_post
  backend/package.json
  cypress/integration/05.Search.feature
  cypress/integration/common/steps.js
  package.json
  webapp/components/Category/Readme.md
  webapp/components/Category/index.spec.js
  webapp/components/Category/index.vue
  webapp/components/Comment.vue
  webapp/components/PostCard.vue
  webapp/components/RelativeDateTime/Readme.md
  webapp/components/RelativeDateTime/index.spec.js
  webapp/components/RelativeDateTime/index.vue
  webapp/components/Tag/Readme.md
  webapp/components/Tag/index.spec.js
  webapp/components/Tag/index.vue
  webapp/components/User/index.spec.js
  webapp/components/User/index.vue
  webapp/package.json
  webapp/pages/post/_id/_slug/index.vue
  webapp/pages/profile/_id/_slug.vue
  webapp/plugins/vue-filters.js
  webapp/yarn.lock
Labels: bug

#406 Don't expose private RSA key
  backend/src/middleware/passwordMiddleware.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/resolvers/user_management.spec.js
Labels: bug

#237 List socialMedia links
  backend/package.json
  backend/src/graphql-schema.js
  backend/src/middleware/index.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/middleware/validUrlMiddleware.js
  backend/src/resolvers/socialMedia.js
  backend/src/resolvers/socialMedia.spec.js
  backend/src/schema.graphql
  cypress/integration/common/settings.js
  cypress/integration/user_profile/SocialMedia.feature
  webapp/graphql/UserProfileQuery.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/profile/_id/_slug.vue
  webapp/pages/settings.vue
  webapp/pages/settings/my-social-media.spec.js
  webapp/pages/settings/my-social-media.vue
  webapp/store/auth.js
Labels: Feature

#439 [WIP] Frontend implementation for notifications
  backend/src/seed/factories/badges.js
  backend/src/seed/factories/categories.js
  backend/src/seed/factories/comments.js
  backend/src/seed/factories/index.js
  backend/src/seed/factories/notifications.js
  backend/src/seed/factories/organizations.js
  backend/src/seed/factories/posts.js
  backend/src/seed/factories/reports.js
  backend/src/seed/factories/tags.js
  backend/src/seed/factories/users.js
  backend/src/seed/seed-db.js
  cypress/README.md
  cypress/features.md
  cypress/integration/common/steps.js
  cypress/integration/notifications/Mentions.feature
  cypress/support/commands.js
  webapp/components/PostCard/index.vue
  webapp/components/PostCard/spec.js
  webapp/components/notifications/Notification/index.vue
  webapp/components/notifications/Notification/spec.js
  webapp/components/notifications/NotificationList/index.vue
  webapp/components/notifications/NotificationList/spec.js
  webapp/components/notifications/NotificationMenu/index.vue
  webapp/components/notifications/NotificationMenu/spec.js
  webapp/layouts/blank.vue
  webapp/layouts/default.vue
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/mixins/seo.js
  webapp/pages/index.vue
  webapp/pages/post/_id/_slug/more-info.vue
  webapp/pages/profile/_id/_slug.vue
  webapp/plugins/vue-filters.js
  webapp/store/auth.js
  webapp/store/notifications.js
Labels: Feature

#485 Refactor maintenance-worker docker image
  SUMMARY.md
  backend/.dockerignore
  backend/db-migration-worker/Dockerfile
  backend/db-migration-worker/README.md
  backend/docker-compose.cypress.yml
  backend/docker-compose.db-migration.yml
  backend/docker-compose.override.yml
  backend/docker-compose.travis.yml
  backend/docker-compose.yml
  deployment/.gitignore
  deployment/README.md
  deployment/configmap.template.yaml
  deployment/db-migration-worker.yaml
  deployment/digital-ocean/README.md
  deployment/digital-ocean/dashboard/README.md
  deployment/digital-ocean/dashboard/admin-user.yaml
  deployment/digital-ocean/dashboard/dashboard-screenshot.png
  deployment/digital-ocean/dashboard/role-binding.yaml
  deployment/digital-ocean/https/README.md
  deployment/digital-ocean/https/ingress.yaml
  deployment/digital-ocean/https/issuer.yaml
  deployment/human-connection/README.md
  deployment/human-connection/deployment-backend.yaml
  deployment/human-connection/deployment-neo4j.yaml
  deployment/legacy-migration/README.md
  deployment/legacy-migration/deployment-backend.yaml
  deployment/legacy-migration/deployment-neo4j.yaml
  deployment/legacy-migration/maintenance-worker.yaml
  deployment/legacy-migration/maintenance-worker/.dockerignore
  deployment/legacy-migration/maintenance-worker/.gitignore
  deployment/legacy-migration/maintenance-worker/Dockerfile
  deployment/legacy-migration/maintenance-worker/binaries/create_private_ssh_key_from_env
  deployment/legacy-migration/maintenance-worker/binaries/import_legacy_db
  deployment/legacy-migration/maintenance-worker/binaries/import_legacy_uploads
  deployment/legacy-migration/maintenance-worker/docker-compose.yml
  deployment/legacy-migration/maintenance-worker/known_hosts
  deployment/legacy-migration/maintenance-worker/migration/mongo/import.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/badges.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/categories.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/comments.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/follows.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/import.sh
  deployment/legacy-migration/maintenance-worker/migration/neo4j/shouts.cql
  deployment/legacy-migration/maintenance-worker/migration/neo4j/users.cql
  deployment/minikube/README.md
  deployment/secrets.template.yaml
  deployment/volumes/README.md
  deployment/volumes/neo4j-data.yaml
  deployment/volumes/uploads.yaml
  docker-compose.yml
  neo4j/Dockerfile
  neo4j/migrate.sh
Labels: Feature

#484 Fix? flaky cypress by waiting for <no-ssr> content
  cypress/integration/common/report.js
  cypress/integration/moderation/ReportContent.feature
  webapp/pages/profile/_id/_slug.vue
Labels: bug

#475 Add Comment Form
  backend/src/graphql-schema.js
  backend/src/middleware/permissionsMiddleware.js
  backend/src/middleware/softDeleteMiddleware.spec.js
  backend/src/resolvers/comments.js
  backend/src/resolvers/comments.spec.js
  backend/src/resolvers/moderation.spec.js
  backend/src/resolvers/socialMedia.js
  backend/src/schema.graphql
  backend/src/seed/factories/comments.js
  backend/src/seed/seed-db.js
  cypress/integration/common/post.js
  cypress/integration/post/Comment.feature
  webapp/components/CommentForm/index.vue
  webapp/components/Editor/index.vue
  webapp/components/Editor/spec.js
  webapp/graphql/CommentQuery.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/post/_id/_slug/index.vue
Labels: Feature
