Repository Human-Connection/Human-Connection, pull requests merged in 2019-09, with the labels that each got.

#1399 🍰 Correct the import of tags from the Alpha and refactor editor hashtags
  backend/package.json
  backend/src/middleware/hashtags/extractHashtags.js
  backend/src/middleware/hashtags/extractHashtags.spec.js
  backend/yarn.lock
  deployment/legacy-migration/maintenance-worker/migration/neo4j/contributions/contributions.cql
  webapp/components/Editor/Editor.vue
  webapp/components/Editor/SuggestionList.vue
  webapp/package.json
  webapp/yarn.lock
Labels: DevOps, bug

#1539 [WIP] Sorting dropdown is aligned with post cards
  webapp/pages/index.vue
Labels: bug

#1533 [WIP] 🍰 Update follower count on follow/unfollow
  webapp/components/FollowButton.vue
  webapp/components/User/User.vue
Labels: backend, bug, frontend

#1571 🍰 Make hashtag links URL safe
  backend/src/middleware/hashtags/extractHashtags.js
  backend/src/middleware/hashtags/extractHashtags.spec.js
  backend/src/middleware/hashtags/hashtagsMiddleware.spec.js
  backend/src/seed/seed-db.js
  webapp/components/Editor/ContentViewer.vue
  webapp/components/Editor/Editor.vue
  webapp/components/Editor/nodes/Hashtag.js
  webapp/components/Editor/nodes/Link.js
  webapp/locales/de.json
  webapp/locales/en.json
  webapp/pages/admin.vue
  webapp/pages/admin/hashtags.vue
  webapp/pages/search/hashtag/_id.vue
Labels: backend, bug, frontend
